# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/dev/AssignmentProject/assignmentproject/file_io

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/dev/AssignmentProject/assignmentproject/file_io/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/dev/AssignmentProject/assignmentproject/file_io/build/CMakeFiles /mnt/c/dev/AssignmentProject/assignmentproject/file_io/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/dev/AssignmentProject/assignmentproject/file_io/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lib_ut_tests

# Build rule for target.
lib_ut_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib_ut_tests
.PHONY : lib_ut_tests

# fast build rule for target.
lib_ut_tests/fast:
	$(MAKE) -f CMakeFiles/lib_ut_tests.dir/build.make CMakeFiles/lib_ut_tests.dir/build
.PHONY : lib_ut_tests/fast

#=============================================================================
# Target rules for targets named myApp

# Build rule for target.
myApp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myApp
.PHONY : myApp

# fast build rule for target.
myApp/fast:
	$(MAKE) -f CMakeFiles/myApp.dir/build.make CMakeFiles/myApp.dir/build
.PHONY : myApp/fast

#=============================================================================
# Target rules for targets named file_io_lib

# Build rule for target.
file_io_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_io_lib
.PHONY : file_io_lib

# fast build rule for target.
file_io_lib/fast:
	$(MAKE) -f CMakeFiles/file_io_lib.dir/build.make CMakeFiles/file_io_lib.dir/build
.PHONY : file_io_lib/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

app/src/main.o: app/src/main.cpp.o

.PHONY : app/src/main.o

# target to build an object file
app/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/myApp.dir/build.make CMakeFiles/myApp.dir/app/src/main.cpp.o
.PHONY : app/src/main.cpp.o

app/src/main.i: app/src/main.cpp.i

.PHONY : app/src/main.i

# target to preprocess a source file
app/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/myApp.dir/build.make CMakeFiles/myApp.dir/app/src/main.cpp.i
.PHONY : app/src/main.cpp.i

app/src/main.s: app/src/main.cpp.s

.PHONY : app/src/main.s

# target to generate assembly for a file
app/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/myApp.dir/build.make CMakeFiles/myApp.dir/app/src/main.cpp.s
.PHONY : app/src/main.cpp.s

lib/src/File_Io.o: lib/src/File_Io.cpp.o

.PHONY : lib/src/File_Io.o

# target to build an object file
lib/src/File_Io.cpp.o:
	$(MAKE) -f CMakeFiles/file_io_lib.dir/build.make CMakeFiles/file_io_lib.dir/lib/src/File_Io.cpp.o
.PHONY : lib/src/File_Io.cpp.o

lib/src/File_Io.i: lib/src/File_Io.cpp.i

.PHONY : lib/src/File_Io.i

# target to preprocess a source file
lib/src/File_Io.cpp.i:
	$(MAKE) -f CMakeFiles/file_io_lib.dir/build.make CMakeFiles/file_io_lib.dir/lib/src/File_Io.cpp.i
.PHONY : lib/src/File_Io.cpp.i

lib/src/File_Io.s: lib/src/File_Io.cpp.s

.PHONY : lib/src/File_Io.s

# target to generate assembly for a file
lib/src/File_Io.cpp.s:
	$(MAKE) -f CMakeFiles/file_io_lib.dir/build.make CMakeFiles/file_io_lib.dir/lib/src/File_Io.cpp.s
.PHONY : lib/src/File_Io.cpp.s

lib/ut/tests.o: lib/ut/tests.cpp.o

.PHONY : lib/ut/tests.o

# target to build an object file
lib/ut/tests.cpp.o:
	$(MAKE) -f CMakeFiles/lib_ut_tests.dir/build.make CMakeFiles/lib_ut_tests.dir/lib/ut/tests.cpp.o
.PHONY : lib/ut/tests.cpp.o

lib/ut/tests.i: lib/ut/tests.cpp.i

.PHONY : lib/ut/tests.i

# target to preprocess a source file
lib/ut/tests.cpp.i:
	$(MAKE) -f CMakeFiles/lib_ut_tests.dir/build.make CMakeFiles/lib_ut_tests.dir/lib/ut/tests.cpp.i
.PHONY : lib/ut/tests.cpp.i

lib/ut/tests.s: lib/ut/tests.cpp.s

.PHONY : lib/ut/tests.s

# target to generate assembly for a file
lib/ut/tests.cpp.s:
	$(MAKE) -f CMakeFiles/lib_ut_tests.dir/build.make CMakeFiles/lib_ut_tests.dir/lib/ut/tests.cpp.s
.PHONY : lib/ut/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lib_ut_tests"
	@echo "... myApp"
	@echo "... file_io_lib"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... app/src/main.o"
	@echo "... app/src/main.i"
	@echo "... app/src/main.s"
	@echo "... lib/src/File_Io.o"
	@echo "... lib/src/File_Io.i"
	@echo "... lib/src/File_Io.s"
	@echo "... lib/ut/tests.o"
	@echo "... lib/ut/tests.i"
	@echo "... lib/ut/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

